"""Update LocalDiagnosis

Revision ID: 03e838b28491
Revises: fd15a3024151
Create Date: 2025-06-21 18:15:42.630191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e838b28491'
down_revision: Union[str, None] = 'fd15a3024151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('local_diagnoses', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.add_column('local_diagnoses', sa.Column('hadm_id', sa.Integer(), nullable=False))
    op.add_column('local_diagnoses', sa.Column('icd_code', sa.String(), nullable=False))
    op.add_column('local_diagnoses', sa.Column('icd_version', sa.Integer(), nullable=True))
    op.add_column('local_diagnoses', sa.Column('seq_num', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_local_diagnoses_id'), table_name='local_diagnoses')
    op.drop_column('local_diagnoses', 'diagnosis_count')
    op.drop_column('local_diagnoses', 'risk_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('local_diagnoses', sa.Column('risk_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('local_diagnoses', sa.Column('diagnosis_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_local_diagnoses_id'), 'local_diagnoses', ['id'], unique=False)
    op.drop_column('local_diagnoses', 'seq_num')
    op.drop_column('local_diagnoses', 'icd_version')
    op.drop_column('local_diagnoses', 'icd_code')
    op.drop_column('local_diagnoses', 'hadm_id')
    op.drop_column('local_diagnoses', 'subject_id')
    # ### end Alembic commands ###
