"""Add serial_id to Envoy

Revision ID: 4a56754e6ab2
Revises: a2ea9b15ee8b
Create Date: 2025-06-21 17:40:58.209245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a56754e6ab2'
down_revision: Union[str, None] = 'a2ea9b15ee8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('envoys', sa.Column('serial_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_envoys_serial_id'), 'envoys', ['serial_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_envoys_serial_id'), table_name='envoys')
    op.drop_column('envoys', 'serial_id')
    # ### end Alembic commands ###
