"""Add s3_output_prefix to Envoy

Revision ID: 69a57c27f90c
Revises: 
Create Date: 2025-06-21 16:59:26.954113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a57c27f90c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('envoys', sa.Column('s3_output_prefix', sa.String(), nullable=True))
    op.drop_column('envoys', 'notebook_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('envoys', sa.Column('notebook_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('envoys', 's3_output_prefix')
    # ### end Alembic commands ###
