"""Add diagnosis_count to LocalDiagnosis

Revision ID: 84e44354d6d6
Revises: 5f4957b74b93
Create Date: 2025-06-21 18:33:30.478500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e44354d6d6'
down_revision: Union[str, None] = '5f4957b74b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('local_diagnoses', sa.Column('diagnosis_count', sa.Integer(), nullable=True))
    op.add_column('local_diagnoses', sa.Column('risk_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('local_diagnoses', 'risk_level')
    op.drop_column('local_diagnoses', 'diagnosis_count')
    # ### end Alembic commands ###
