"""Description Type

Revision ID: a2ea9b15ee8b
Revises: 69a57c27f90c
Create Date: 2025-06-21 17:08:10.563273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ea9b15ee8b'
down_revision: Union[str, None] = '69a57c27f90c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('envoys', sa.Column('s3_bucket', sa.String(), nullable=True))
    op.add_column('envoys', sa.Column('s3_prefix', sa.String(), nullable=True))
    op.add_column('envoys', sa.Column('region', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('envoys', 'region')
    op.drop_column('envoys', 's3_prefix')
    op.drop_column('envoys', 's3_bucket')
    # ### end Alembic commands ###
