"""Add created_at to LocalDiagnosis

Revision ID: fd15a3024151
Revises: 4a56754e6ab2
Create Date: 2025-06-21 17:56:40.132076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd15a3024151'
down_revision: Union[str, None] = '4a56754e6ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('local_diagnoses', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('local_diagnoses', 'created_at')
    # ### end Alembic commands ###
